- name:  Ne Pas Autoriser les connexion entrante
  become: true
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Set logging
  ufw:
    logging: 'on'

- name:  Configuration du par-feux du serveur web [SSH]
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    direction: in
    log: true

- name:  Configuration du par-feux du serveur web [http]
  community.general.ufw:
    rule: limit
    port: 80
    proto: tcp
    direction: in
    log: true

- name:  Configuration du par feu du serveur web [https]
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
    direction: in
    log: true