---
- name: Deploy existing WordPress site
  hosts: all
  become: yes
  vars:
    wp_db_name: mydb
    wp_db_user: myuser
    wp_db_password: mypassword
    wp_db_host: localhost
    wp_url: numeration.com
    wp_title: numeration
    backup_dir: /path/to/backup/dir
  tasks:
    - name: Download and Extract existing WordPress site
      unarchive:
        src: /wordpress/numeration.tar.gz
        dest: /var/www/html/
        remote_src: true

    - name: Update existing WordPress config file
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'database_name_here'
        replace: "{{ wp_db_name }}"
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'username_here'
        replace: "{{ wp_db_user }}"
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'password_here'
        replace: "{{ wp_db_password }}"
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'localhost'
        replace: "{{ wp_db_host }}"

