---
- name: Deploy existing WordPress site
  hosts: all
  become: yes
  vars:
    wp_db_name: mydb
    wp_db_user: myuser
    wp_db_password: mypassword
    wp_db_host: localhost
    wp_url: numeration.com
    wp_title: numeration
    backup_dir: /path/to/backup/dir
    mariadb_root_password: "password"
    mariadb_db_name: "mydb"
    mariadb_db_file: "mydb.sql"
  tasks:
    - name: Download and Extract existing WordPress site
      unarchive:
        src: /wordpress/numeration.tar.gz
        dest: /var/www/html/
        remote_src: true

    - name: Update Wordpress conf bd_name
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'bd_numeration'
        replace: "{{ wp_db_name }}"

    - name: Update Wordpress conf bd_user
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'root'
        replace: "{{ wp_db_user }}"

    - name: Update Wordpress conf bd_password
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: "''"
        replace: "'{{ wp_db_password }}'"

    - name: Update Wordpress conf bd_host
      replace:
        path: /var/www/html/numeration/wp-config.php
        regexp: 'localhost'
        replace: "{{ wp_db_host }}"

### COPIES DE LA BDD SUR LE SERVER BDD
    - name: Import MariaDB database
      shell: mysql -u root -p{{ mariadb_root_password }} {{ mariadb_db_name }} < {{ mariadb_db_file }}
