- include_vars: ../var_file.yml

- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Crée l'utilisateur pour le wordPress
  mysql_user:
    name: "{{db_user}}"
    host: "%"
    password: "{{root_password}}"
    priv: "{{db_name}}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password:
    state: present
  become: true

- name: Configure un accès distance sur la bdd
  become: true
  become_user: root
  lineinfile:
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'

- name: Restart Mysql
  become: true
  service:
    name: mysql
    state: restarted

- name: Set password admin root

  mysql_user:
    name: root
    host: localhost
    password: "Johny$English2023"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password:
    state: absent
  become: true

- name: Copie du script sql de la bdd wordPress
  copy:
    src: wordpress/bd_numeration.sql
    dest: /home/vagrant

- name: Création de la basse de donnée
  become: true
  mysql_db:
    name: "{{db_name}}"
    state: present
    login_user: "{{db_user}}"
    login_password: "{{root_password}}"

- name: Import de la BDD wordPress
  shell: mysql -u {{db_user}} -p{{ root_password }} {{ db_name }} < {{ db_file }}