- name:  Ne Pas Autoriser les connexion entrante
  become: true
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name:  Configuration du par-feux du serveur bdd [SSH]
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
    direction: in

- name: Configuration du par-feux du serveur bdd [3306]
  community.general.ufw:
    rule: allow
    port: 3306
    proto: tcp
    src : 192.168.56.32
    direction: in
#    state: enabled
#- name : Configuration du par-feux de la bbd
#  community.general.ufw:
#    rule: allow
#    port: 3306
#    proto: tcp
#    direction: in
#    src: 192.168.56.32
#    from_port: 8080
#    dest: 192.168.56.36
#    to_port: 3306
#    log: true
#- name: Ne Pas Autoriser les connexion sortante
#  become: true
#  community.general.ufw:
#    state: enabled
#    policy: deny
#    direction: outgoing