  - name: Install and configure WordPress
    hosts: httpNumerisation
    become: true
    vars:
      wp_db_name: mydb
      wp_db_user: myuser
      wp_db_password: mypassword
      wp_db_host: localhost
      wp_admin_user: admin
      wp_admin_password: admin_password
      wp_admin_email: admin@example.com
      wp_url: numeration.com
      wp_title: numeration
    tasks:
      - name: "Install apache2"
        package: name=apache2 state=present
          - name: "Install apache2-php7.4"
            package: name=libapache2-mod-php7.4 state=present
          - name: "Install php7.4-cli"
            package: name=php7.4-cli state=present
          - name: "Install php7.4-mcrypt"
            package: name=php7.4-mcrypt state=present
          - name: "Install php7.4-gd"
            package: name=php7.4-gd state=present
          - name: Install php7.4-fpm
            package: name=php7.4-fpm state=present
          - name: Install php7.4-common
            package: name=php7.4-common state=present
          - name: Install php7.4-mbstring
            package: name=php7.4-mbstring state=present
          - name: Install php7.4-xmlrpc
            package: name=php7.4-xmlrpc state=present
          - name: Install php7.4-xml
            package: name=php7.4-xml state=present
          - name: Install php7.4-mysql
            package: name=php7.4-mysql state=present
          - name: Install php7.4-zip
            package: name=php7.4-zip state=present
          - name: Install php7.4-curl
            package: name=php7.4-curl state=present
#      - name: Download WordPress
#        get_url:
#          url: https://wordpress.org/latest.tar.gz
#          dest: /tmp/latest.tar.gz
#      - name: Extract WordPress
#        unarchive:
#          src: /tmp/latest.tar.gz
#          dest: /var/www/html/
#      - name: Create WordPress database
#        mysql_db:
#          name: "{{ wp_db_name }}"
#          state: present
#          login_user: root
#          login_password: "{{ mysql_root_password }}"
#      - name: Create WordPress database user
#        mysql_user:
#          name: "{{ wp_db_user }}"
#          host: "{{ wp_db_host }}"
#          password: "{{ wp_db_password }}"
#          priv: "{{ wp_db_name }}.*:ALL"
#          state: present
#      - name: Configure wp-config.php
#        template:
#          src: wp-config.php.j2
#          dest: /var/www/html/wordpress/wp-config.php
#          mode: 0644
#      - name: Run WordPress installation script
#        shell: |
#          chown -R www-data:www-data /var/www/html/wordpress
#          echo "{{ wp_url }} {{ ansible_fqdn }}" >> /etc/hosts
#          curl -s -d "weblog_title={{ wp_title }}&user_name={{ wp_admin_user }}&admin_password={{ wp_admin_password }}&admin_password2={{ wp_admin_password }}&admin_email={{ wp_admin_email }}&Submit=Install+WordPress&language=" http://{{ wp_url }}/wordpress/wp-admin/install.php?step=2


