---
- name: Provisionner VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - import_tasks: 2/user_and_group.yml

- name: HTTP Numerisation
  hosts: http # Numerisation
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    - import_tasks: 3/dependences_wordpress.yml
    - import_tasks: 4/automatisation_wordpress_deploiment.yml

- name: BDD Numerisationq
  hosts: bdd # Numerisation
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - var_file.yml
  tasks:
    - import_tasks: 3/dependences_bdd.yml