- name: Verifier que le groupe 'devops' existe
  group:
    name: devops
    state: present

- name: Creer utilisateur 'web'
  user:
    name: web
    shell: /bin/bash
    password: $6$OStSJfA6FA$ffSDaJBWfSpmnwlC6QWJwLG3PgZWQhPYUSezmRvSiUFpwSWy/57KuUuLg/4yGBpKx2TWYsPDz9Yq7nL2I2XT3/

- name: Assigner 'web' au groupe 'devops'
  user:
    name: web
    groups: devops
    append: yes