- name: Verifier que le groupe 'devops' existe
  group:
    name: devops
    state: present

- name: Creer utilisateur 'user_wordpress'
  user:
    name: user_wordpress
    shell: /bin/bash
    password: $6$OStSJfA6FA$ffSDaJBWfSpmnwlC6QWJwLG3PgZWQhPYUSezmRvSiUFpwSWy/57KuUuLg/4yGBpKx2TWYsPDz9Yq7nL2I2XT3/

- name: Assigner 'user_wordpress' au groupe 'devops'
  user:
    name: user_wordpress
    groups: devops
    append: yes